# Generated by Django 5.0.4 on 2024-04-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
