# Generated by Django 5.0.4 on 2024-05-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_rename_phone_user_campusphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='room_number',
        ),
    ]
