# Generated by Django 5.0.4 on 2024-05-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_remove_user_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='room number'),
        ),
    ]
