# Generated by Django 5.0.3 on 2024-04-12 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the course', max_length=10, unique=True)),
                ('title', models.CharField(help_text='Title of the course', max_length=100)),
                ('description', models.TextField(help_text='Description of the course')),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], help_text='Semester in which the course is offered', max_length=10)),
                ('year', models.IntegerField(help_text='Year in which the course is offered')),
                ('instructor', models.ForeignKey(help_text='Instructor assigned to the course', limit_choices_to={'role': 'Instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
                ('tas', models.ManyToManyField(blank=True, help_text='TAs assigned to the course', limit_choices_to={'role': 'TA'}, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
