# Generated by Django 5.0.3 on 2024-04-12 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10)),
                ('schedule', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sections', to='course_management.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_assignments', to=settings.AUTH_USER_MODEL)),
                ('lab_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lab_section_management.labsection')),
            ],
        ),
    ]
