# Generated by Django 5.0.3 on 2024-04-12 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
        ('lab_section_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labsection',
            name='location',
        ),
        migrations.RemoveField(
            model_name='labsection',
            name='section_number',
        ),
        migrations.AddField(
            model_name='labsection',
            name='number',
            field=models.CharField(default=20, help_text='Lab section number or identifier.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labsection',
            name='tas',
            field=models.ManyToManyField(blank=True, help_text='TAs assigned to this lab section.', limit_choices_to={'role': 'TA'}, related_name='lab_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='course',
            field=models.ForeignKey(help_text='The course this lab section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lab_sections', to='course_management.course'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='schedule',
            field=models.CharField(help_text='Schedule or timing details for the lab section.', max_length=50),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
